=== MinimalistPeach/AQYO8L_XMLGyak/AQYO8L_1004/AQYO8L_orarend.dtd
<!ELEMENT AQYO8L_Orarend (ora*)>
<!ELEMENT ora (targy, idopont, helyszin, oktato, szak*)>
<!ELEMENT targy (#PCDATA)>
<!ELEMENT helyszin (#PCDATA)>
<!ELEMENT oktato (#PCDATA)>
<!ELEMENT szak (#PCDATA)>
<!ELEMENT idopont (nap, mettol, meddig)>
<!ELEMENT nap (#PCDATA)>
<!ELEMENT mettol (#PCDATA)>
<!ELEMENT meddig (#PCDATA)>
<!ATTLIST ora id ID #REQUIRED
                tipus (eloadas|gyakorlat) "eloadas">

=== MinimalistPeach/AQYO8L_XMLGyak/AQYO8L_1004/AQYO8L_orarend.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE AQYO8L_Orarend SYSTEM "AQYO8L_orarend.dtd">
<AQYO8L_Orarend>
    <ora id="_1" tipus="eloadas">
        <targy> WEB-Technológiák </targy>
        <idopont>
            <nap> Hétfő </nap>
            <mettol> 14:00 </mettol>
            <meddig> 15:30 </meddig>
        </idopont>
        <helyszin> XXX.előadó </helyszin>
        <oktato> Agárdi Anita </oktato>

        <szak>Programtervező Informatikus</szak>
        <szak>Mérnök Informatikus</szak>

    </ora>

    <ora id="_2" tipus="gyakorlat">
        <targy> WEB-Technológiák gyakorlat</targy>
        <idopont>
            <nap> Hétfő </nap>
            <mettol> 16:00 </mettol>
            <meddig> 17:30 </meddig>
        </idopont>
        <helyszin> In/202 </helyszin>
        <oktato> Agárdi Anita </oktato>

        <szak>Programtervező Informatikus</szak>
        <szak>Mérnök Informatikus</szak>

    </ora>

    <ora id="_3" tipus="eloadas">
        <targy> Mesterséges intellmeddigencia alapok </targy>
        <idopont>
            <nap> Kedd </nap>
            <mettol> 10:00 </mettol>
            <meddig> 11:30 </meddig>
        </idopont>
        <helyszin> XXXII.előadó </helyszin>
        <oktato> Fazekas Levente Áron </oktato>

        <szak>Programtervező Informatikus</szak>
        <szak>Mérnök Informatikus</szak>

    </ora>

    <ora id="_4" tipus="eloadas">
        <targy> Adatkezelés XML-ben </targy>
        <idopont>
            <nap> Kedd </nap>
            <mettol> 12:00 </mettol>
            <meddig> 13:30 </meddig>
        </idopont>
        <helyszin> XXXII.előadó </helyszin>
        <oktato> Dr. Bednarik László </oktato>

        <szak>Programtervező Informatikus</szak>
        <szak>Mérnök Informatikus</szak>

    </ora>

    <ora id="_5" tipus="eloadas">
        <targy> Algoritmusok és vizsgálatuk </targy>
        <idopont>
            <nap> Kedd </nap>
            <mettol> 14:00 </mettol>
            <meddig> 17:30 </meddig>
        </idopont>
        <helyszin> A1/320 </helyszin>
        <oktato> Dr. Házy Attila </oktato>

        <szak>Programtervező Informatikus</szak>

    </ora>

    <ora id="_6" tipus="gyakorlat">
        <targy> Adatkezelés XML-ben </targy>
        <idopont>
            <nap> Szerda </nap>
            <mettol> 12:00 </mettol>
            <meddig> 13:30 </meddig>
        </idopont>
        <helyszin> In/103 </helyszin>
        <oktato> Dr. Bednarik László </oktato>

        <szak>Programtervező Informatikus</szak>
        <szak>Mérnök Informatikus</szak>

    </ora>

    <ora id="_7" tipus="gyakorlat">
        <targy> Adatkezelés XML-ben </targy>
        <idopont>
            <nap> Szerda </nap>
            <mettol> 12:00 </mettol>
            <meddig> 13:30 </meddig>
        </idopont>
        <helyszin> In/103 </helyszin>
        <oktato> Dr. Bednarik László </oktato>

        <szak>Programtervező Informatikus</szak>
        <szak>Mérnök Informatikus</szak>

    </ora>

    <ora id="_8" tipus="eloadas">
        <targy> Vállalati információs rendszerek fejlesztése </targy>
        <idopont>
            <nap> Szerda </nap>
            <mettol> 14:00 </mettol>
            <meddig> 15:30 </meddig>
        </idopont>
        <helyszin> In/101 </helyszin>
        <oktato> Dr. Sasvári Péter László </oktato>

        <szak>Programtervező Informatikus</szak>
        <szak>Mérnök Informatikus</szak>

    </ora>

    <ora id="_9" tipus="gyakorlat">
        <targy> Vállalati információs rendszerek fejlesztése </targy>
        <idopont>
            <nap> Szerda </nap>
            <mettol> 18:00 </mettol>
            <meddig> 19:30 </meddig>
        </idopont>
        <helyszin> In/103 </helyszin>
        <oktato> Dr. Sasvári Péter László </oktato>

        <szak>Programtervező Informatikus</szak>
        <szak>Mérnök Informatikus</szak>

    </ora>

    <ora id="_10" tipus="gyakorlat">
        <targy> Mesterséges intellmeddigencia alapok </targy>
        <idopont>
            <nap> Csütörtök </nap>
            <mettol> 10:00 </mettol>
            <meddig> 11:30 </meddig>
        </idopont>
        <helyszin> I.előadó </helyszin>
        <oktato> Fazekas Levente Áron </oktato>

        <szak>Programtervező Informatikus</szak>
        <szak>Mérnök Informatikus</szak>

    </ora>
</AQYO8L_Orarend>
