=== MinimalistPeach/AQYO8L_XMLGyak/XMLTaskAQYO8L/1.feladat/XMLSchemaAQYO8L.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Aruhaz-beszallito_AQYO8L">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Aruhazak">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Aruhaz" maxOccurs="unbounded" minOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Nev" type="xs:string" />
                                        <xs:element name="Cim">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Iranyitoszam"
                                                        type="xs:integer" />
                                                    <xs:element name="Telepules" type="xs:string" />
                                                    <xs:element name="Utca" type="xs:string" />
                                                    <xs:element name="Hazszam" type="xs:string" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute type="xs:integer" name="aruhazid" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="Beszallitok">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Beszallito" maxOccurs="unbounded" minOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Nev" type="xs:string" />
                                        <xs:element name="Termek_kategoria" type="xs:string" />
                                        <xs:element name="Atlagos_szallitasi_ido">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:integer">
                                                        <xs:attribute name="mertekegyseg">
                                                            <xs:simpleType>
                                                                <xs:restriction base="xs:string">
                                                                    <xs:enumeration value="ora" />
                                                                    <xs:enumeration value="perc" />
                                                                    <xs:enumeration value="nap" />
                                                                    <xs:enumeration value="het" />
                                                                </xs:restriction>
                                                            </xs:simpleType>
                                                        </xs:attribute>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute type="xs:integer" name="beszallitoid"
                                        use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="Raktarak">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Aruhaz_Raktar_Termek" maxOccurs="unbounded"
                                minOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Nev" type="xs:string" />
                                        <xs:element name="Darabszam" type="xs:integer" />
                                        <xs:element name="Kategoria">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="Elektronika" />
                                                    <xs:enumeration value="Élelmiszer" />
                                                    <xs:enumeration value="Építőanyag" />
                                                    <xs:enumeration value="Gépjármű alkatrész" />
                                                    <xs:enumeration value="Bútor" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="Ar">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="penznem">
                                                            <xs:simpleType>
                                                                <xs:restriction base="xs:string">
                                                                    <xs:enumeration value="huf" />
                                                                    <xs:enumeration value="eu" />
                                                                </xs:restriction>
                                                            </xs:simpleType>
                                                        </xs:attribute>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute type="xs:integer" name="termekid" use="required" />
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="Beszallito_Raktar_Termek" maxOccurs="unbounded"
                                minOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Nev" type="xs:string" />
                                        <xs:element name="Darabszam" type="xs:integer" />
                                        <xs:element name="Kategoria">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="Elektronika" />
                                                    <xs:enumeration value="Élelmiszer" />
                                                    <xs:enumeration value="Építőanyag" />
                                                    <xs:enumeration value="Gépjármű alkatrész" />
                                                    <xs:enumeration value="Bútor" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute type="xs:integer" name="termekid" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="Akcios_Termekek">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Akcios_Termek" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Nev" type="xs:string" />
                                        <xs:element name="Leiras" type="xs:string" />
                                        <xs:element name="Kategoria">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="Elektronika" />
                                                    <xs:enumeration value="Élelmiszer" />
                                                    <xs:enumeration value="Építőanyag" />
                                                    <xs:enumeration value="Gépjármű alkatrész" />
                                                    <xs:enumeration value="Bútor" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="Arak" maxOccurs="1">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Eredeti_ar">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:double">
                                                                    <xs:attribute name="penznem">
                                                                        <xs:simpleType>
                                                                            <xs:restriction
                                                                                base="xs:string">
                                                                                <xs:enumeration
                                                                                    value="huf" />
                                                                                <xs:enumeration
                                                                                    value="eu" />
                                                                            </xs:restriction>
                                                                        </xs:simpleType>
                                                                    </xs:attribute>
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="Akcios_ar">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:double">
                                                                    <xs:attribute name="penznem">
                                                                        <xs:simpleType>
                                                                            <xs:restriction
                                                                                base="xs:string">
                                                                                <xs:enumeration
                                                                                    value="huf" />
                                                                                <xs:enumeration
                                                                                    value="eu" />
                                                                            </xs:restriction>
                                                                        </xs:simpleType>
                                                                    </xs:attribute>
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute type="xs:integer" name="termekid" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== MinimalistPeach/AQYO8L_XMLGyak/XMLTaskAQYO8L/2.feladat/domparseaqyo8l/src/main/java/hu/domparse/aqyo8l/XMLAQYO8L_2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Aruhaz-beszallito_AQYO8L xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="XMLSchemaAQYO8L.xsd">
    <!-- Áruházak létrehozása és adatai megadása-->
    <Aruhazak>
        <!--Első
        áruház és adatai-->
        <Aruhaz aruhazid="1">
            <Nev>Tesco</Nev>
            <Cim>
                <Iranyitoszam>3544</Iranyitoszam>
                <Telepules>Miskolc</Telepules>
                <Utca>Karakter utca</Utca>
                <Hazszam>12</Hazszam>
            </Cim>
        </Aruhaz>

        <!--Második
        áruház és adatai-->
        <Aruhaz aruhazid="2">
            <Nev>Auchan</Nev>
            <Cim>
                <Iranyitoszam>1138</Iranyitoszam>
                <Telepules>Budapest</Telepules>
                <Utca>Lehel utca</Utca>
                <Hazszam>5</Hazszam>
            </Cim>
        </Aruhaz>

        <!--Harmadik
        áruház és adatai-->
        <Aruhaz aruhazid="3">
            <Nev>Spar</Nev>
            <Cim>
                <Iranyitoszam>6722</Iranyitoszam>
                <Telepules>Szeged</Telepules>
                <Utca>Arany János utca</Utca>
                <Hazszam>3</Hazszam>
            </Cim>
        </Aruhaz>
    </Aruhazak>

    <Beszallitok>
        <!-- Beszállítók létrehozása és adatai megadása-->
        <Beszallito beszallitoid="1">
            <Nev>Kerékroncs KFT.</Nev>
            <Termek_kategoria>Gépjármű alkatrész</Termek_kategoria>
            <Atlagos_szallitasi_ido mertekegyseg="perc">48</Atlagos_szallitasi_ido>
        </Beszallito>

        <Beszallito beszallitoid="2">
            <Nev>Építőanyag KFT.</Nev>
            <Termek_kategoria>Építőanyag</Termek_kategoria>
            <Atlagos_szallitasi_ido mertekegyseg="ora">2</Atlagos_szallitasi_ido>
        </Beszallito>

        <Beszallito beszallitoid="3">
            <Nev>Elektronikai KFT.</Nev>
            <Termek_kategoria>Elektronika</Termek_kategoria>
            <Atlagos_szallitasi_ido mertekegyseg="ora">5</Atlagos_szallitasi_ido>
        </Beszallito>
    </Beszallitok>

    <!-- Áruház-Beszállító több:több kapcsolat megvalósítása-->

    <Aruhaz-Beszallito aruhazid="1" beszallitoid="2">
        <Atlagos_Rendelt_Arumennyiseg>2</Atlagos_Rendelt_Arumennyiseg>
    </Aruhaz-Beszallito>

    <Aruhaz-Beszallito aruhazid="2" beszallitoid="3">
        <Atlagos_Rendelt_Arumennyiseg>15</Atlagos_Rendelt_Arumennyiseg>
    </Aruhaz-Beszallito>

    <Aruhaz-Beszallito aruhazid="3" beszallitoid="1">
        <Atlagos_Rendelt_Arumennyiseg>8</Atlagos_Rendelt_Arumennyiseg>
    </Aruhaz-Beszallito>

    <Raktarak>
        <!-- Áruház raktárak és adataik-->
        <Aruhaz_Raktar_Termek aruhazid="1" termekid="1">
            <Nev>Rántotthús</Nev>
            <Darabszam>2</Darabszam>
            <Kategoria>Élelmiszer</Kategoria>
            <Ar penznem="huf">1200</Ar>
        </Aruhaz_Raktar_Termek>
        <Aruhaz_Raktar_Termek aruhazid="1" termekid="2">
            <Nev>Tej</Nev>
            <Darabszam>10</Darabszam>
            <Kategoria>Élelmiszer</Kategoria>
            <Ar penznem="huf">300</Ar>
        </Aruhaz_Raktar_Termek>
        <Aruhaz_Raktar_Termek aruhazid="2" termekid="3">
            <Nev>Asztal</Nev>
            <Darabszam>5</Darabszam>
            <Kategoria>Bútor</Kategoria>
            <Ar penznem="huf">15000</Ar>
        </Aruhaz_Raktar_Termek>

        <!-- Beszállító raktárak és adataik-->
        <Beszallito_Raktar_Termek beszallitoid="1" termekid="1">
            <Nev>Autóalkatrész</Nev>
            <Darabszam>50</Darabszam>
            <Kategoria>Gépjármű alkatrész</Kategoria>
        </Beszallito_Raktar_Termek>
        <Beszallito_Raktar_Termek beszallitoid="2" termekid="2">
            <Nev>Csempe</Nev>
            <Darabszam>100</Darabszam>
            <Kategoria>Építőanyag</Kategoria>
        </Beszallito_Raktar_Termek>
        <Beszallito_Raktar_Termek beszallitoid="3" termekid="3">
            <Nev>Laptop</Nev>
            <Darabszam>20</Darabszam>
            <Kategoria>Elektronika</Kategoria>
        </Beszallito_Raktar_Termek>
    </Raktarak>

    <Akcios_Termekek>
        <!-- Akciós termékek és adataik-->
        <Akcios_Termek akciostermekid="1" termekid="1">
            <Nev>Farhát</Nev>
            <Leiras>Finom farhát</Leiras>
            <Kategoria>Élelmiszer</Kategoria>
            <Arak>
                <Eredeti_ar penznem="huf">1200.00</Eredeti_ar>
                <Eredeti_ar penznem="eu">4.00</Eredeti_ar>
                <Akcios_ar penznem="huf">1100.00</Akcios_ar>
                <Akcios_ar penznem="eu">3.75</Akcios_ar>
            </Arak>
        </Akcios_Termek>
        <Akcios_Termek akciostermekid="2" termekid="2">
            <Nev>Tej</Nev>
            <Leiras>Friss tej</Leiras>
            <Kategoria>Élelmiszer</Kategoria>
            <Arak>
                <Eredeti_ar penznem="huf">300.00</Eredeti_ar>
                <Eredeti_ar penznem="eu">1.00</Eredeti_ar>
                <Akcios_ar penznem="huf">250.00</Akcios_ar>
                <Akcios_ar penznem="eu">0.85</Akcios_ar>
            </Arak>
        </Akcios_Termek>
        <Akcios_Termek akciostermekid="3" termekid="3">
            <Nev>Asztal</Nev>
            <Leiras>Igényes asztal</Leiras>
            <Kategoria>Bútor</Kategoria>
            <Arak>
                <Eredeti_ar penznem="huf">15000.00</Eredeti_ar>
                <Eredeti_ar penznem="eu">50.00</Eredeti_ar>
                <Akcios_ar penznem="huf">12000.00</Akcios_ar>
                <Akcios_ar penznem="eu">40.8</Akcios_ar>
            </Arak>

        </Akcios_Termek>
        <Akcios_Termek akciostermekid="4" termekid="4">
            <Nev>Autóalkatrész</Nev>
            <Leiras>Minőségi alkatrész</Leiras>
            <Kategoria>Gépjármű alkatrész</Kategoria>
            <Arak>
                <Eredeti_ar penznem="huf">5000.0</Eredeti_ar>
                <Eredeti_ar penznem="eu">17.0</Eredeti_ar>
                <Akcios_ar penznem="huf">4500.0</Akcios_ar>
                <Akcios_ar penznem="eu">15.3</Akcios_ar>
            </Arak>
        </Akcios_Termek>
        <Akcios_Termek akciostermekid="5" termekid="5">
            <Nev>Csempe</Nev>
            <Leiras>Stílusos csempe</Leiras>
            <Kategoria>Építőanyag</Kategoria>
            <Arak>
                <Eredeti_ar penznem="huf">2000.0</Eredeti_ar>
                <Eredeti_ar penznem="eu">6.8</Eredeti_ar>
                <Akcios_ar penznem="huf">1800.0</Akcios_ar>
                <Akcios_ar penznem="eu">6.12</Akcios_ar>
            </Arak>
        </Akcios_Termek>
    </Akcios_Termekek>

</Aruhaz-beszallito_AQYO8L>
